import { afterAll, beforeAll, describe, expect, test } from 'bun:test';

import { PGlite } from '@electric-sql/pglite';
import { type SQL } from 'drizzle-orm';
import { integer, PgDialect, pgTable, serial } from 'drizzle-orm/pg-core';
import { z } from 'zod';

import { pg_jsonschema } from '../dist/index.js';
import { jsonbCheck } from '../src/drizzle.js';

const dialect = new PgDialect();

async function createDb(): Promise<PGlite> {
  const pg = await PGlite.create({
    extensions: { pg_jsonschema: pg_jsonschema() },
  });
  try {
    await pg.exec('CREATE EXTENSION IF NOT EXISTS pg_jsonschema;');
  } catch (err) {
    const pgVersion = (await pg.query<{ v: string }>('SELECT version() AS v')).rows[0]?.v;
    throw new Error(
      `Failed to load the built pg_jsonschema.so into PGlite.\n` +
        `PGlite reports: ${pgVersion}\n` +
        `The .so in dist/ must be compiled against PG headers (vendor/postgres/include) ` +
        `matching that exact major version, or PGlite rejects it as an incompatible module.\n` +
        `Original error: ${err instanceof Error ? err.message : String(err)}`
    );
  }
  return pg;
}

/** Evaluate a single `jsonb_matches_schema(val, schema)` call. */
async function matches(pg: PGlite, val: string, schema: string): Promise<boolean | null> {
  const res = await pg.query<{ r: boolean | null }>('SELECT jsonb_matches_schema($1, $2) AS r', [
    val,
    schema,
  ]);
  return res.rows[0]?.r ?? null;
}

describe('pg_jsonschema extension in PGlite', () => {
  let pg: PGlite;

  beforeAll(async () => {
    pg = await createDb();
  });

  afterAll(async () => {
    await pg?.close();
  });

  test('the extension installs and registers jsonb_matches_schema', async () => {
    const res = await pg.query<{ exists: boolean }>(
      `SELECT EXISTS (
         SELECT 1 FROM pg_proc WHERE proname = 'jsonb_matches_schema'
       ) AS exists`
    );
    expect(res.rows[0]?.exists).toBe(true);
  });

  test('accepts a document that satisfies the schema', async () => {
    expect(await matches(pg, '{"a":1}', '{"type":"object","required":["a"]}')).toBe(true);
  });

  test('rejects a document that violates the schema', async () => {
    expect(await matches(pg, '{"b":1}', '{"type":"object","required":["a"]}')).toBe(false);
  });

  test('validates primitive types, enums and numeric bounds', async () => {
    expect(await matches(pg, '5', '{"type":"integer","minimum":1,"maximum":10}')).toBe(true);
    expect(await matches(pg, '50', '{"type":"integer","maximum":10}')).toBe(false);
    expect(await matches(pg, '"green"', '{"enum":["red","green","blue"]}')).toBe(true);
    expect(await matches(pg, '"pink"', '{"enum":["red","green","blue"]}')).toBe(false);
  });

  test('is STRICT: a NULL argument yields NULL, not an error', async () => {
    const res = await pg.query<{ r: boolean | null }>(
      'SELECT jsonb_matches_schema(NULL, $1) AS r',
      ['{"type":"object"}']
    );
    expect(res.rows[0]?.r).toBeNull();
  });

  test('enforces a CHECK constraint built from a JSON schema', async () => {
    await pg.exec(`
      CREATE TABLE events (
        id   serial PRIMARY KEY,
        data text NOT NULL,
        CONSTRAINT data_is_valid
          CHECK (jsonb_matches_schema(data, '{"type":"object","required":["name"]}'))
      );
    `);

    await pg.exec(`INSERT INTO events (data) VALUES ('{"name":"launch"}')`);
    const ok = await pg.query<{ c: number }>('SELECT count(*)::int AS c FROM events');
    expect(ok.rows[0]?.c).toBe(1);

    await expect(
      pg.exec(`INSERT INTO events (data) VALUES ('{"missing":"name"}')`)
    ).rejects.toThrow(/data_is_valid|check constraint/i);
  });

  test('enforces a CHECK constraint generated by the drizzle export', async () => {
    const schema = z.object({ sku: z.string(), qty: z.number().int() });
    const table = pgTable('products', { id: serial(), payload: integer() });
    const constraint = jsonbCheck('payload_schema', table.payload, schema);
    const checkSql = renderCheck(constraint, table);

    // Build a text column and apply the drizzle-generated predicate to it.
    await pg.exec(`
      CREATE TABLE products (
        id      serial PRIMARY KEY,
        payload text NOT NULL
      );
    `);
    // Re-point the predicate at the real text column instead of the placeholder.
    const predicate = checkSql.replaceAll('"products"."payload"', 'payload');
    await pg.exec(`ALTER TABLE products ADD CONSTRAINT payload_schema CHECK (${predicate})`);

    await pg.exec(`INSERT INTO products (payload) VALUES ('{"sku":"A1","qty":3}')`);
    await expect(pg.exec(`INSERT INTO products (payload) VALUES ('{"sku":"A1"}')`)).rejects.toThrow(
      /payload_schema|check constraint/i
    );
  });
});

/** Render a drizzle check constraint expression to raw SQL. */
function renderCheck(builder: unknown, table: object): string {
  const built = (builder as { build(t: object): { value: SQL } }).build(table);
  return dialect.sqlToQuery(built.value).sql;
}
